/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JTable;
import javax.swing.*;
import controller.controllerHistory;

/**
 *
 * @author HP
 */
public class history extends javax.swing.JFrame {

    /**
     * Creates new form history
     */
   
    
    controllerHistory ch;
    public history() {
        initComponents();
      ch = new controllerHistory(this);
      ch.isiHistory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHistory = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTxtJumlah = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnRegis = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCBServis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCBDevice = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Servis", "Nama Pelanggan", "Tanggal", "No Telepon", "Jenis Device", "Nama Device", "Jenis Service", "Deskripsi", "Total Biaya", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelHistory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 740, 360));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Servis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 80, 80, -1));

        jTxtJumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 73, 130, 30));

        jPanel2.setBackground(new java.awt.Color(99, 122, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegis.setBackground(new java.awt.Color(99, 122, 159));
        btnRegis.setForeground(new java.awt.Color(255, 255, 255));
        btnRegis.setText("Registrasi Servis");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 170, 49));

        btnBayar.setBackground(new java.awt.Color(99, 122, 159));
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("Pembayaran");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 330, 180, 49));

        btnRiwayat.setBackground(new java.awt.Color(99, 122, 159));
        btnRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        btnRiwayat.setText("Riwayat");
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });
        jPanel2.add(btnRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 170, 49));

        btnExit.setBackground(new java.awt.Color(99, 122, 159));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 170, 49));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 140));

        jLabel12.setBackground(new java.awt.Color(62, 118, 185));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hallo! Admin 1");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 520));

        jPanel1.setBackground(new java.awt.Color(116, 155, 194));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("History");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 790, 50));

        jCBServis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servis Ringan", "Servis Sedang", "Servis Berat", "Semua" }));
        jCBServis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBServisActionPerformed(evt);
            }
        });
        getContentPane().add(jCBServis, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Data");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Device");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 80, -1));

        jCBDevice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "PC", "Smartphone", "Speaker", "Proyektor", "Monitor", "Tv", "Printer", "CCTV", "Semua" }));
        jCBDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDeviceActionPerformed(evt);
            }
        });
        getContentPane().add(jCBDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgservis.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        new pembayaran().show();
        dispose();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        new registrasi().show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisActionPerformed

    private void jTxtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtJumlahActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void jCBServisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBServisActionPerformed
        // TODO add your handling code here:
        ch.isiHistory();
    }//GEN-LAST:event_jCBServisActionPerformed

    private void jCBDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDeviceActionPerformed
        // TODO add your handling code here:
        ch.isiHistory();
    }//GEN-LAST:event_jCBDeviceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegis;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JComboBox<String> jCBDevice;
    private javax.swing.JComboBox<String> jCBServis;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtJumlah;
    private javax.swing.JTable tabelHistory;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelHistory() {
        return tabelHistory;
    }

    public void setTabelHistory(JTable tabelHistory) {
        this.tabelHistory = tabelHistory;
    }

    public JTextField getjTxtJumlah() {
        return jTxtJumlah;
    }

    public void setjTxtJumlah(JTextField jTxtJumlah) {
        this.jTxtJumlah = jTxtJumlah;
    }

    public JComboBox<String> getjCBDevice() {
        return jCBDevice;
    }

    public void setjCBDevice(JComboBox<String> jCBDevice) {
        this.jCBDevice = jCBDevice;
    }

    public JComboBox<String> getjCBServis() {
        return jCBServis;
    }

    public void setjCBServis(JComboBox<String> jCBServis) {
        this.jCBServis = jCBServis;
    }
    
    

    
}
