/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import controller.datascontroller;
import javax.swing.JComboBox;

/**
 *
 * @author LENOVO
 */
public class registrasi extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
    datascontroller dc;

    public registrasi() {
        initComponents();
        dc = new datascontroller(this);

        dc.isitabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnNama = new javax.swing.JTextField();
        btnTgl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNomor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnJenisdevice = new javax.swing.JComboBox<>();
        btnStatus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnNamaDevice = new javax.swing.JTextField();
        btnJenisservis = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnDeskripsi = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Servis", "Nama Pelanggan", "Tanggal", "Telepon", "Jenis Device", "Nama Device", "Jenis Servis", "Deskripsi", "Total Biaya", "ID Status", "Keterangan"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 299, 740, 200));

        jPanel2.setBackground(new java.awt.Color(99, 122, 159));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(62, 118, 185));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hallo! Admin 1");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 20));

        jButton3.setBackground(new java.awt.Color(99, 122, 159));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registrasi Servis");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 170, 50));

        jButton2.setBackground(new java.awt.Color(99, 122, 159));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pembayaran");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 170, 50));

        jButton1.setBackground(new java.awt.Color(99, 122, 159));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Riwayat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 170, 50));

        jButton4.setBackground(new java.awt.Color(99, 122, 159));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 140));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 520));

        jPanel3.setBackground(new java.awt.Color(213, 233, 245));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(62, 118, 185));
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("ID Servis");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        btnID.setEditable(false);
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });
        jPanel3.add(btnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Nama Pelanggan");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        btnNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamaActionPerformed(evt);
            }
        });
        jPanel3.add(btnNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, -1));

        btnTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTglActionPerformed(evt);
            }
        });
        jPanel3.add(btnTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Tanggal");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 84, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Nomor Telepon");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        btnNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomorActionPerformed(evt);
            }
        });
        jPanel3.add(btnNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Jenis Device");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 84, -1));

        btnJenisdevice.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnJenisdevice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "PC", "Smartphone", "Speaker", "Proyektor", "Monitor", "Tv", "Printer", "CCTV" }));
        btnJenisdevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJenisdeviceActionPerformed(evt);
            }
        });
        jPanel3.add(btnJenisdevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, -1));

        btnStatus.setEditable(false);
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        jPanel3.add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 110, 50));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Status");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 110, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText("Nama Device");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 84, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setText("Jenis Servis");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 84, -1));

        btnNamaDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamaDeviceActionPerformed(evt);
            }
        });
        jPanel3.add(btnNamaDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 180, -1));

        btnJenisservis.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnJenisservis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servis Ringan", "Servis Sedang", "Servis Berat" }));
        btnJenisservis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJenisservisActionPerformed(evt);
            }
        });
        jPanel3.add(btnJenisservis, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 180, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setText("Deskripsi Servis");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 110, -1));

        btnDeskripsi.setColumns(20);
        btnDeskripsi.setRows(5);
        jScrollPane1.setViewportView(btnDeskripsi);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 180, 50));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setText("Total Biaya");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 84, -1));

        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        jPanel3.add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 180, -1));

        jButton5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton5.setText("Tambah");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 40));

        jButton6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton6.setText("Ubah");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 130, 40));

        jButton7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton7.setText("Hapus");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 130, 40));

        jButton8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 130, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 790, 470));

        jPanel1.setBackground(new java.awt.Color(116, 155, 194));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrasi Servis");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 790, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        history h = new history();
//        h.setVisible(true);
//        h.setLocationRelativeTo(null);
        new history().show();
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new pembayaran().show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        btnID.setText(jTable1.getValueAt(baris, 0).toString());
        btnNama.setText(jTable1.getValueAt(baris, 1).toString());
        btnTgl.setText(jTable1.getValueAt(baris, 2).toString());
        btnNomor.setText(jTable1.getValueAt(baris, 3).toString());
        btnJenisdevice.setSelectedItem(jTable1.getValueAt(baris, 4).toString());
        btnNamaDevice.setText(jTable1.getValueAt(baris, 5).toString());
        btnJenisservis.setSelectedItem(jTable1.getValueAt(baris, 6).toString());
        btnDeskripsi.setText(jTable1.getValueAt(baris, 7).toString());
        btnTotal.setText(jTable1.getValueAt(baris, 8).toString());
        btnStatus.setText(jTable1.getValueAt(baris, 9).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dc.reset();
        dc.isitabel();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dc.delete();
        dc.isitabel();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dc.update();
        dc.isitabel();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dc.insert();
        dc.isitabel();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnJenisservisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJenisservisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJenisservisActionPerformed

    private void btnNamaDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamaDeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNamaDeviceActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnJenisdeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJenisdeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJenisdeviceActionPerformed

    private void btnNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNomorActionPerformed

    private void btnTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTglActionPerformed

    private void btnNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNamaActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea btnDeskripsi;
    private javax.swing.JTextField btnID;
    private javax.swing.JComboBox<String> btnJenisdevice;
    private javax.swing.JComboBox<String> btnJenisservis;
    private javax.swing.JTextField btnNama;
    private javax.swing.JTextField btnNamaDevice;
    private javax.swing.JTextField btnNomor;
    private javax.swing.JTextField btnStatus;
    private javax.swing.JTextField btnTgl;
    private javax.swing.JTextField btnTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextArea getBtnDeskripsi() {
        return btnDeskripsi;
    }

    public JTextField getBtnID() {
        return btnID;
    }

    public JTextField getBtnNama() {
        return btnNama;
    }

    public JTextField getBtnNamaDevice() {
        return btnNamaDevice;
    }

    public JTextField getBtnNomor() {
        return btnNomor;
    }

    public JTextField getBtnStatus() {
        return btnStatus;
    }

    public JTextField getBtnTgl() {
        return btnTgl;
    }

    public JTextField getBtnTotal() {
        return btnTotal;
    }

    public void setBtnDeskripsi(JTextArea btnDeskripsi) {
        this.btnDeskripsi = btnDeskripsi;
    }

    public void setBtnID(JTextField btnID) {
        this.btnID = btnID;
    }

    public JComboBox<String> getBtnJenis() {
        return btnJenisdevice;
    }

    public void setBtnJenis(JComboBox<String> btnJenis) {
        this.btnJenisdevice = btnJenis;
    }

    public void setBtnNama(JTextField btnNama) {
        this.btnNama = btnNama;
    }

    public void setBtnNamaDevice(JTextField btnNamaDevice) {
        this.btnNamaDevice = btnNamaDevice;
    }

    public void setBtnNomor(JTextField btnNomor) {
        this.btnNomor = btnNomor;
    }

    public void setBtnStatus(JTextField btnStatus) {
        this.btnStatus = btnStatus;
    }

    public void setBtnTgl(JTextField btnTgl) {
        this.btnTgl = btnTgl;
    }

    public void setBtnTotal(JTextField btnTotal) {
        this.btnTotal = btnTotal;
    }

    public JComboBox<String> getBtnJenisServis() {
        return btnJenisdevice;
    }

    public void setBtnJenisServis(JComboBox<String> btnJenisServis) {
        this.btnJenisdevice = btnJenisServis;
    }

    public JComboBox<String> getBtnJenisdevice() {
        return btnJenisdevice;
    }

    public void setBtnJenisdevice(JComboBox<String> btnJenisdevice) {
        this.btnJenisdevice = btnJenisdevice;
    }

    public JComboBox<String> getBtnJenisservis() {
        return btnJenisservis;
    }

    public void setBtnJenisservis(JComboBox<String> btnJenisservis) {
        this.btnJenisservis = btnJenisservis;
    }

}
